version: 2

before:
  hooks:
    - go mod download
    - go run ./src/version/versiongenerator/version-gen.go

builds:
  # Session Manager Plugin
  - id: session-manager-plugin
    main: ./src/sessionmanagerplugin-main/main.go
    binary: session-manager-plugin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "6"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    flags:
      - -trimpath

  # SSM CLI
  - id: ssmcli
    main: ./src/ssmcli-main/main.go
    binary: ssmcli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    flags:
      - -trimpath

  # SSM Port Forward
  - id: ssm-port-forward
    main: ./src/ssm-port-forward-main/main.go
    binary: ssm-port-forward
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    flags:
      - -trimpath

archives:
  - id: plugin-archives
    ids:
      - session-manager-plugin
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - NOTICE
      - README.md
      - RELEASENOTES.md
      - THIRD-PARTY
      - VERSION

  - id: ssmcli-archives
    ids:
      - ssmcli
    name_template: >-
      ssmcli_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - NOTICE
      - README.md
      - RELEASENOTES.md
      - THIRD-PARTY

  - id: ssm-port-forward-archives
    ids:
      - ssm-port-forward
    name_template: >-
      ssm-port-forward_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - NOTICE
      - README.md

nfpms:
  # DEB packages
  - id: plugin-deb
    package_name: session-manager-plugin
    ids:
      - session-manager-plugin
    vendor: Amazon
    homepage: https://github.com/aws/session-manager-plugin
    maintainer: AWS Systems Manager <aws-ssm-feedback@amazon.com>
    description: Session Manager Plugin for the AWS CLI
    license: Apache-2.0
    formats:
      - deb
    bindir: /usr/local/sessionmanagerplugin/bin
    contents:
      - src: packaging/ubuntu_plugin/session-manager-plugin.conf
        dst: /etc/init/session-manager-plugin.conf
      - src: packaging/ubuntu_plugin/session-manager-plugin.service
        dst: /lib/systemd/system/session-manager-plugin.service
      - src: LICENSE
        dst: /usr/local/sessionmanagerplugin/LICENSE
      - src: NOTICE
        dst: /usr/local/sessionmanagerplugin/NOTICE
      - src: README.md
        dst: /usr/local/sessionmanagerplugin/README.md
      - src: RELEASENOTES.md
        dst: /usr/local/sessionmanagerplugin/RELEASENOTES.md
      - src: THIRD-PARTY
        dst: /usr/local/sessionmanagerplugin/THIRD-PARTY
      - src: VERSION
        dst: /usr/local/sessionmanagerplugin/VERSION

  # RPM packages
  - id: plugin-rpm
    package_name: session-manager-plugin
    ids:
      - session-manager-plugin
    vendor: Amazon
    homepage: https://github.com/aws/session-manager-plugin
    maintainer: AWS Systems Manager <aws-ssm-feedback@amazon.com>
    description: Session Manager Plugin for the AWS CLI
    license: Apache-2.0
    formats:
      - rpm
    bindir: /usr/local/sessionmanagerplugin/bin
    contents:
      - src: packaging/linux_plugin/session-manager-plugin.conf
        dst: /etc/init/session-manager-plugin.conf
      - src: packaging/linux_plugin/session-manager-plugin.service
        dst: /usr/lib/systemd/system/session-manager-plugin.service
      - src: LICENSE
        dst: /usr/local/sessionmanagerplugin/LICENSE
      - src: NOTICE
        dst: /usr/local/sessionmanagerplugin/NOTICE
      - src: README.md
        dst: /usr/local/sessionmanagerplugin/README.md
      - src: RELEASENOTES.md
        dst: /usr/local/sessionmanagerplugin/RELEASENOTES.md
      - src: THIRD-PARTY
        dst: /usr/local/sessionmanagerplugin/THIRD-PARTY
      - src: VERSION
        dst: /usr/local/sessionmanagerplugin/VERSION

checksum:
  name_template: "checksums.txt"

homebrew_casks:
  - name: session-manager-plugin
    repository:
      owner: zph
      name: session-manager-plugin
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Casks
    homepage: https://github.com/zph/session-manager-plugin
    description: Session Manager Plugin for the AWS CLI
    license: Apache-2.0
    url:
      verified: github.com/zph/session-manager-plugin
    ids:
      - plugin-archives
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/session-manager-plugin"]
          end

  - name: ssmcli
    repository:
      owner: zph
      name: session-manager-plugin
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Casks
    homepage: https://github.com/zph/session-manager-plugin
    description: SSM CLI tool for AWS Session Manager
    license: Apache-2.0
    url:
      verified: github.com/zph/session-manager-plugin
    ids:
      - ssmcli-archives
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssmcli"]
          end

  - name: ssm-port-forward
    repository:
      owner: zph
      name: session-manager-plugin
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Casks
    homepage: https://github.com/zph/session-manager-plugin
    description: SSH-style port forwarding for AWS SSM sessions with multi-hop support
    license: Apache-2.0
    url:
      verified: github.com/zph/session-manager-plugin
    ids:
      - ssm-port-forward-archives
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssm-port-forward"]
          end

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
  mode: replace
  footer: |
    ## Installation

    See [README.md](https://github.com/aws/session-manager-plugin/blob/master/README.md) for installation instructions.
