# This file was generated by GoReleaser. DO NOT EDIT.
cask "session-manager-plugin" do
  name "session-manager-plugin"
  desc "Session Manager Plugin for the AWS CLI"
  homepage "https://github.com/zph/session-manager-plugin"
  version "0.0.0-1.2.694.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "session-manager-plugin"

  on_macos do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/session-manager-plugin_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "08a96e83ae943d00de03fd9ec0a7ad1fce4d55a0a8614c8628575f280d8ed0fb"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/session-manager-plugin_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "86904547240e3fbf910ff346f54d3d4ab53c472c1ad921f58f15b0f988583967"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/session-manager-plugin_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "b9c65492eb943cea2b1353a93e12ff92deadea39395bdf1d3661427ac61623b0"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/session-manager-plugin_#{version}_linux_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "e77755d4639554133c2b75777a38315a1a14a0c19a6439f003deaa4918b74699"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/session-manager-plugin"]
    end
  end

  # No zap stanza required
end
