# This file was generated by GoReleaser. DO NOT EDIT.
cask "session-manager-plugin" do
  name "session-manager-plugin"
  desc "Session Manager Plugin for the AWS CLI"
  homepage "https://github.com/zph/session-manager-plugin"
  version "0.0.0-1.2.694.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "session-manager-plugin"

  on_macos do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/session-manager-plugin_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "441c0d8f7b36d819cdf1420800c9f0a09eda2d41de9c4f990669841dd2e8cf69"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/session-manager-plugin_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "338f3ca7ea664a09ceb0c50823818b5d1af917b9fa441c5977ef44ad785b4535"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/session-manager-plugin_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "ea1f6d0337c490fdf5baa0efcdf0276b8242fa85a66f6deac67b8296c81b6288"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/session-manager-plugin_#{version}_linux_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "475518b4bc077804a06f107fdfaf1673a2cd3caa4c5463b3797444800d7f0eed"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/session-manager-plugin"]
    end
  end

  # No zap stanza required
end
