# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssm-port-forward" do
  name "ssm-port-forward"
  desc "SSH-style port forwarding for AWS SSM sessions with multi-hop support"
  homepage "https://github.com/zph/session-manager-plugin"
  version "0.0.0-1.2.694.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssm-port-forward"

  on_macos do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssm-port-forward_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "203d7ed2882640db15fdf6b26399d33e4d7f092deec9a1d55bb5a55e8d6c9916"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssm-port-forward_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "19ce576f93e86f1865834fa2a3c278d33a0772f21e12131c3295ca54f0c20fba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssm-port-forward_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "22800bfd3ba8c02677110bc3b0e0a078778e27a1f33b1d546ff0637e69cfb8b6"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssm-port-forward_#{version}_linux_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "a73e27dbd46f6c970122a3a5115c0992a03e72651a340e219a4dbf1a7f034d5c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssm-port-forward"]
    end
  end

  # No zap stanza required
end
