# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssm-port-forward" do
  name "ssm-port-forward"
  desc "SSH-style port forwarding for AWS SSM sessions with multi-hop support"
  homepage "https://github.com/zph/session-manager-plugin"
  version "0.0.0-1.2.694.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssm-port-forward"

  on_macos do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssm-port-forward_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "7c3f15cd3b2d50bdbbd5fc713286729d163d26c3a93cfa7a175c886f624acbdd"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssm-port-forward_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "5e4776cb83fff444188497c1bfa7b09f4000401fc05bdde13f97c23caf89e668"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssm-port-forward_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "7ebbf01ee09df528304efd90f6c093560f503ef9056f6fbf5cd25d8106629f24"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssm-port-forward_#{version}_linux_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "f5bbea9c608a448fb81acae6cbd3f6da0562460a665fe99d0014d1c183ef026c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssm-port-forward"]
    end
  end

  # No zap stanza required
end
