# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssm-port-forward" do
  name "ssm-port-forward"
  desc "SSH-style port forwarding for AWS SSM sessions with multi-hop support"
  homepage "https://github.com/zph/session-manager-plugin"
  version "0.0.0-1.2.694.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssm-port-forward"

  on_macos do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssm-port-forward_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "74af1d396a7cb17ebced338653aef8982c02bc225f55eb311f50fe103b87608d"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssm-port-forward_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "c23563a5ea29223a9a962a1cfda503c225d2dff2e942a9a1b0e728503bc08340"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssm-port-forward_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "52cd855e41803d942240a753f405a68b8193f97defea6e1c2d43dd9a12ef8212"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssm-port-forward_#{version}_linux_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "1422cd719544ff171a40f365879e14d422e069792bec5072a08143a4efb5c0f9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssm-port-forward"]
    end
  end

  # No zap stanza required
end
