# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssmcli" do
  name "ssmcli"
  desc "SSM CLI tool for AWS Session Manager"
  homepage "https://github.com/zph/session-manager-plugin"
  version "0.0.0-1.2.694.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssmcli"

  on_macos do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssmcli_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "bebd545d2e3ba7137a4d25d46ef7e85ba6e82beab5150b49ac57dc836db64f98"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssmcli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "f6822a56b454e80249cfd8a08916bba932b0107d234bbabc3a6c818b5328ff68"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssmcli_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "d4c349001af540e1beac07961e43fcc6db29963a7a42ac710996d533e0e8f269"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssmcli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "ce91d59409783e53d82204e959f46e6d92c32b16269446e4100593c41387ace6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssmcli"]
    end
  end

  # No zap stanza required
end
