# This file was generated by GoReleaser. DO NOT EDIT.
cask "ssmcli" do
  name "ssmcli"
  desc "SSM CLI tool for AWS Session Manager"
  homepage "https://github.com/zph/session-manager-plugin"
  version "0.0.0-1.2.694.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ssmcli"

  on_macos do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssmcli_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "981e38002868aad69a1fc8a445d47df30ea51c72d4b9eff6fbe936fac02f393a"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssmcli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "950cae9e58b9592741eb3a1c28385c4ad9001fca94d68b9c12fbcf32a1a7b942"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssmcli_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "c0938ae95e2d1e88ba96c2b0c6fc4b3da0fc182bfe8bec38ab6d4e935928805e"
    end
    on_arm do
      url "https://github.com/zph/session-manager-plugin/releases/download/v#{version}/ssmcli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/zph/session-manager-plugin"
      sha256 "394d592b243ad674d853cae54a22d7876ae5c504f1a902b4689632ff814fdc56"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ssmcli"]
    end
  end

  # No zap stanza required
end
